version: '3.7'
services:
    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        volumes:
            - mariadb_data:/var/lib/mysql/
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'
        networks:
                mynet:
    
    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: database
        volumes:
            - phpmyadmin_data:/var/www/html/
        networks:
            - mynet
        depends_on:
            - mariadb
networks:
  mynet:

volumes:
  mariadb_data:
  phpmyadmin_data:
 
        